[WIP] Create view :messages screen
Queenieaman/chat-space pull request #2
Opened 2019-05-11 11:19 UTC by Queenieaman

# WHAT
Create Messages Screen view
Using Sass(SCSS code) and HAML
チャット投稿画面の実装

# WHY
It is a main part of this application.
ユーザーが最初に必要とする画面であるため。

2019-05-11 11:26 UTC, i-date reviewed
ご提出ありがとうございます！コメントいたしました^^
また、画面確認のためにスクショを載せていただけないでしょうか？

2019-05-11 11:26 UTC, i-date commented on app/assets/stylesheets/_main_content.scss
> +}
最下行に空行を挿入してあげましょう。

2019-05-11 11:26 UTC, i-date commented on app/assets/stylesheets/_mixin.scss
> +}
こちらも

2019-05-11 11:26 UTC, i-date commented on app/assets/stylesheets/_side_bar.scss
> +}
こちらも

2019-05-11 11:26 UTC, i-date commented on app/assets/stylesheets/_variables.scss
> +$btn-color: #38AEF0;
こちらも

2019-05-11 11:26 UTC, i-date commented on app/assets/stylesheets/application.scss
> +// @import "flash";
コメントアウト箇所は不要でしたら削除しましょう。
また、最下行に空行を挿入してあげましょう。

2019-05-11 11:26 UTC, i-date commented on app/views/layouts/application.html.haml
> +    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.8.1/css/all.css", :integrity => "sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf", :re
ハッシュロケット（=>）は古い記法なので、シンボル型にしましょう。

2019-05-11 11:26 UTC, i-date commented on app/views/messages/index.html.haml
> +        %p.group__latest-message Sample message
繰り返し使用するので、15-23行目を部分テンプレートに切り出してはいかがでしょう？

2019-05-11 11:26 UTC, i-date commented on app/views/messages/index.html.haml
> +          %p.lower-info__text Coming to REIWA
38-55行目も部分テンプレートに切り出してはいかがでしょう？

2019-05-11 11:26 UTC, i-date commented on app/views/messages/index.html.haml
> +      %input.submit-btn__image{:type => "submit", :value => "Send"}
最下行に空行を挿入してあげましょう。

2019-05-12 03:15 UTC, Queenieaman commented on app/views/messages/index.html.haml
> +      %input.submit-btn__image{:type => "submit", :value => "Send"}
最下部に空行を挿入しました

2019-05-12 03:15 UTC, Queenieaman commented on app/views/messages/index.html.haml
> +          %p.lower-info__text Coming to REIWA
38-55行目の繰り返しの部分を部分テンプレート（_message.html.haml)に切り出しました。

2019-05-12 03:15 UTC, Queenieaman commented on app/views/messages/index.html.haml
> +        %p.group__latest-message Sample message
15-23行目の繰り返しの部分を部分テンプレート（_group.html.haml)に切り出しました。

2019-05-12 03:15 UTC, Queenieaman commented on app/views/layouts/application.html.haml
> +    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.8.1/css/all.css", :integrity => "sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf", :re
ハッシュロケットをシンボル型に変更しました。

2019-05-12 03:15 UTC, Queenieaman commented on app/assets/stylesheets/application.scss
> +// @import "flash";
現在不要なコメントアウト箇所を削除し、最下部に空行を挿入しました

2019-05-12 03:15 UTC, Queenieaman commented on app/assets/stylesheets/_variables.scss
> +$btn-color: #38AEF0;
最下部に空行を挿入しました

2019-05-12 03:15 UTC, Queenieaman commented on app/assets/stylesheets/_side_bar.scss
> +}
最下部に空行を挿入しました

2019-05-12 03:15 UTC, Queenieaman commented on app/assets/stylesheets/_mixin.scss
> +}
最下部に空行を挿入しました

2019-05-12 03:15 UTC, Queenieaman commented on app/assets/stylesheets/_main_content.scss
> +}
最下部に空行を挿入しました

2019-05-12 03:16 UTC, Queenieaman commented
スクショ、忘れてまし！失礼しました。

2019-05-12 03:43 UTC, ken-nag reviewed
最終行改行がうまくいっていないですね、、、
editerの自動挿入機能を使いましょう

2019-05-12 04:11 UTC, Queenieaman commented on app/assets/stylesheets/_variables.scss
> +$btn-color: #38AEF0;
setting.Jsonにて　"files.insertFinalNewline": true　を記載の上、最下部に空行を挿入しました。

2019-05-12 04:40 UTC, Queenieaman commented
Variablesのみunsolvedでしたが、念為全てのfileをアップデートしました。

2019-05-12 04:42 UTC, ghost requested changes

2019-05-12 04:42 UTC, hiroki5123 commented on app/views/layouts/application.html.haml
> +    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.8.1/css/all.css", :integrity => "sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf", :re
gem入れているので不要だと思います。
削除しましょう

2019-05-12 04:52 UTC, Queenieaman commented on app/views/layouts/application.html.haml
> +    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.8.1/css/all.css", :integrity => "sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf", :re
## Comment
こちらを削除するとFontaswomeのアイコンが消えてしまいます。bundle installを再度行ってみたり、Gem Listで入っていることは確認し、他の方とRuby, Fontawsome, Railsなどのバージョンも同じことを確認しました。
また、Fontawsomeの最新のバージョンがFontawesome SassGemを入れないと対応されないとのことでこちらも入れてもみましたが改善されなかったので、CONTACTにてご相談させていただきましたが、そのままだしていただいても結構です、とのことでしたので提出させていただきました。

## Amend
ロケット記述箇所を修正しました。

2019-05-12 04:59 UTC, nagatomokent commented on app/views/layouts/application.html.haml
> +    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.8.1/css/all.css", :integrity => "sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf", :re
https://logist3.com/rails5-font-awesome/
こちらの記事のような使用方法をしてもfontawesomeのアイコンが消えてしまいますか？

2019-05-12 05:27 UTC, Queenieaman commented on app/views/layouts/application.html.haml
> +    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.8.1/css/all.css", :integrity => "sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf", :re
消えてしまいます。一応こちらのCSSの表記も試したのですが、ダメでした。https://github.com/bokmann/font-awesome-rails

2019-05-12 06:13 UTC, hiroki5123 commented on app/views/layouts/application.html.haml
> +    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.8.1/css/all.css", :integrity => "sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf", :re
承知しました。
application.scssに
import "font-awesome";
とかくと、うまくいくと思うのでそれで一回試してみてうまくいかなかったらそのままで大丈夫です。

2019-05-12 06:13 UTC, hiroki5123 commented
一度確認をしてそれでダメだったら再度レビュー申請を御願いします。

2019-05-12 06:22 UTC, Queenieaman commented on app/views/layouts/application.html.haml
> +    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.8.1/css/all.css", :integrity => "sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf", :re
importはすでに記載しておりますので、URLを適用して再度レビュー申請させていただきました。
![image](https://user-images.githubusercontent.com/49942420/57578555-a6f78a80-74c9-11e9-8c1b-a74740b6ebd7.png)

2019-05-12 06:27 UTC, Queenieaman commented
ご教示いただいた解決できず恐縮ですが、元々のURLを適用して表示する形で、再度レビュー申請させていただきました。

2019-05-12 07:07 UTC, Queenieaman commented
再度別の方法でやってみます。

2019-05-12 07:18 UTC, Queenieaman commented on app/views/layouts/application.html.haml
> +    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.8.1/css/all.css", :integrity => "sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf", :re
URLを削除しました。

2019-05-12 08:00 UTC, nagatomokent commented
お疲れ様でした、lgtmです

2019-05-12 09:15 UTC, merged